In [139]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [141]:
df = pd.read_excel(r"C:\Users\LENOVO\Downloads\messy_patient_data_.xlsx")

In [143]:
df

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit
0,PID1000,Patient_0,71,Male,12/13-2023,"Sep 13, 2024",42535,2018-03-13 00:00:00,10.11.2023,20213-01-01
1,PID1001,Patient_1,34,Male,16-10-2024,05 August 2023,43008,2016-10-25 00:00:00,29 April 2024,01/06/2024
2,PID1010,Patient_2,57,Female,"April 31, 2022",2016-11-11 00:00:00,43120,2018-06-25 00:00:00,04/May/2023,01/02/03
3,PID1100,Patient_3,24,Female,03/21/2024,13.04.2024,43120,2018-06-25 00:00:00,2024/09/10,04/12/2023
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,43120,2017-04-22 00:00:00,04/Apr/2023,04/12/2023
...,...,...,...,...,...,...,...,...,...,...
127,PID1095,Patient_127,54,Female,12/13-2023,2018-12-10 00:00:00,2018-12-14 00:00:00,20213-01-01,20240520,45019
128,PID1096,Patient_128,84,Male,NaN,2017-11-26 00:00:00,2018-12-15 00:00:00,13-Dec-2024,2023-03-24,16-Mar-2024
129,PID1097,Patient_129,66,Male,2024/07/03,2017-11-26 00:00:00,2018-12-16 00:00:00,?,18.03.2024,NaN
130,PID1098,Patient_130,22,Male,18.10.2024,2016-11-18 00:00:00,2018-12-17 00:00:00,04-Apr-2024,NaN,46184
131,PID1099,Patient_131,20,Female,2023/04/25,2023/05/15,2018-12-17 00:00:00,01/02/03,NaN,45472

In [145]:
def clean_date(val):
    try:
        return pd.to_datetime(val, errors='coerce').date()
    except:
        try:
            return parser.parse(str(val), fuzzy=True).date()
        except:
            return pd.NaT
            
date_columns = ['Date_of_Admission', 'Date_of_Diagnosis', 'Date_of_Treatment_Start','Date_of_Surgery', 'Date_of_Discharge', 'Follow_up_Visit']

for col in date_columns:
    df[col] = df[col].apply(clean_date)
df.replace({'N/A': pd.NA, 'Unknown': pd.NA}, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30676\2374433508.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(val, errors='coerce').date()
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30676\2374433508.py:3: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(val, errors='coerce').date()
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30676\2374433508.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(val, errors='coerce').date()

In [147]:
df

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12
...,...,...,...,...,...,...,...,...,...,...
127,PID1095,Patient_127,54,Female,2023-12-13,2018-12-10,2018-12-14,NaT,2024-05-20,1970-01-01
128,PID1096,Patient_128,84,Male,NaT,2017-11-26,2018-12-15,2024-12-13,2023-03-24,2024-03-16
129,PID1097,Patient_129,66,Male,2024-07-03,2017-11-26,2018-12-16,NaT,2024-03-18,NaT
130,PID1098,Patient_130,22,Male,2024-10-18,2016-11-18,2018-12-17,2024-04-04,NaT,1970-01-01
131,PID1099,Patient_131,20,Female,2023-04-25,2023-05-15,2018-12-17,2003-01-02,NaT,1970-01-01

In [149]:
df.head()

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12

In [151]:
##1. What is the average age of patients?

In [153]:
df['Age'].mean()

52.88636363636363

In [155]:
##2. What is the gender distribution among patients?

In [157]:
df['Gender'].value_counts()

Gender
Female    67
Male      65
Name: count, dtype: int64

In [159]:
##3. Which age group has the highest number of admissions?

In [161]:
bins = [20, 30, 40, 50, 60, 70, 80, 85]

In [163]:
labels = ['20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-84']

In [165]:
df["Age groups"] = pd.cut(df['Age'], bins = bins, labels = labels, right= False)

In [167]:
df.head()

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit,Age groups
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT,70-79
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06,30-39
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02,50-59
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12,20-29
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12,30-39

In [169]:
df.groupby("Age groups")["Date_of_Admission"].count().idxmax()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30676\1175256020.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age groups")["Date_of_Admission"].count().idxmax()

'20-29'

In [171]:
##5. What is the average length of stay (admission to discharge)?

In [173]:
df['Date_of_Admission'] = pd.to_datetime(df['Date_of_Admission'])

In [175]:
df['Date_of_Discharge'] = pd.to_datetime(df['Date_of_Discharge'])

In [177]:
df['Length of Stay(Days)'] = (df['Date_of_Discharge'] - df['Date_of_Admission']).dt.days.astype('Int64')

In [179]:
df.loc[df['Length of Stay(Days)'] < 0, 'Length of Stay(Days)'] = 0

In [181]:
df['Length of Stay(Days)'].mean()

235.32584269662922

In [183]:
df.head()

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit,Age groups,Length of Stay(Days)
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT,70-79,0
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06,30-39,0
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02,50-59,<NA>
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12,20-29,173
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12,30-39,0

In [185]:
##6. How many patients were admitted each month or year?

In [187]:
df["Month Admitted"] = df['Date_of_Admission'].dt.month.astype('Int64')

In [189]:
df['Year Admitted'] =df['Date_of_Admission'].dt.year.astype('Int64')

In [191]:
mapping = { 1 : "Jan", 2: "Feb", 3 : "Mar", 4 : "April", 5:"May" , 6: "June", 7: "July", 8 : "Aug", 9 :"Sep", 10 : "Oct", 11 : "Nov", 12: "Dec"}
df["Month Admitted"] = df["Month Admitted"].map(mapping)

In [193]:
Patients_admitted_each_month  = df.groupby("Month Admitted")["Patient_ID"].count().reset_index(name = "No of Patients Admitted")
Patients_admitted_each_month

   Month Admitted  No of Patients Admitted
0           April                        6
1             Aug                        8
2             Dec                       31
3             Feb                        8
4             Jan                       10
5            July                        6
6            June                       10
7             Mar                       12
8             May                       10
9             Nov                        6
10            Oct                        8
11            Sep                        8

In [195]:
Patients_admitted_each_year = df.groupby("Year Admitted")["Patient_ID"].count().reset_index(name = "No of Patients Admitted")
Patients_admitted_each_year

   Year Admitted  No of Patients Admitted
0           2003                        1
1           2022                        1
2           2023                       72
3           2024                       49

In [197]:
df.head()

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit,Age groups,Length of Stay(Days),Month Admitted,Year Admitted
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT,70-79,0,Dec,2023
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06,30-39,0,Oct,2024
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02,50-59,<NA>,NaN,<NA>
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12,20-29,173,Mar,2024
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12,30-39,0,April,2024

In [199]:
##4. Are there any outliers in patient ages?

In [201]:
Q1  =df['Age'].quantile(0.25)
Q3  =df['Age'].quantile(0.75)
IQR = Q3 -  Q1

In [203]:
outliers_iqr = df[(df["Age"] < (Q1 - 1.5 * IQR)) | (df["Age"] > (Q3 + 1.5 * IQR))]
outliers_iqr

Empty DataFrame
Columns: [Patient_ID, Name, Age, Gender, Date_of_Admission, Date_of_Diagnosis, Date_of_Treatment_Start, Date_of_Surgery, Date_of_Discharge, Follow_up_Visit, Age groups, Length of Stay(Days), Month Admitted, Year Admitted]
Index: []

In [205]:
"""There are no outliers in the Patients Ages"""

'There are no outliers in the Patients Ages'

In [207]:
##8. What percentage of patients have missing or invalid admission/discharge dates?

In [209]:
df.head()

,Patient_ID,Name,Age,Gender,Date_of_Admission,Date_of_Diagnosis,Date_of_Treatment_Start,Date_of_Surgery,Date_of_Discharge,Follow_up_Visit,Age groups,Length of Stay(Days),Month Admitted,Year Admitted
0,PID1000,Patient_0,71,Male,2023-12-13,2024-09-13,1970-01-01,2018-03-13,2023-10-11,NaT,70-79,0,Dec,2023
1,PID1001,Patient_1,34,Male,2024-10-16,2023-08-05,1970-01-01,2016-10-25,2024-04-29,2024-01-06,30-39,0,Oct,2024
2,PID1010,Patient_2,57,Female,NaT,2016-11-11,1970-01-01,2018-06-25,2023-05-04,2003-01-02,50-59,<NA>,NaN,<NA>
3,PID1100,Patient_3,24,Female,2024-03-21,2024-04-13,1970-01-01,2018-06-25,2024-09-10,2023-04-12,20-29,173,Mar,2024
4,PID1101,Patient_4,33,Male,2024-04-09,2023-03-16,1970-01-01,2017-04-22,2023-04-04,2023-04-12,30-39,0,April,2024

In [211]:
invalid_dates = df["Date_of_Admission"].isna() | df["Date_of_Discharge"].isna()
missing_percentage = (invalid_dates.sum() / len(df)) * 100
missing_percentage.round(2)

32.58

In [213]:
##Which patients have the longest and shortest hospital stays?

In [215]:
longest_stay = df.groupby("Patient_ID")['Length of Stay(Days)'].sum().idxmax()
shortest_stay = df.groupby("Patient_ID")['Length of Stay(Days)'].sum().idxmin()
longest_stay, shortest_stay

('PID1103', 'PID1000')